# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "production" branch
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo /opt/puppetlabs/puppet/bin/r10k deploy environment -p  
          

  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build

    steps:
      - name: Send Telegram Message Ok
        uses: appleboy/telegram-action@master
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Puppet wait</b>
            <b>Build is finished</b>
            Repository: ${{ github.repository }}
            Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
            Author: ${{ github.actor }}
            Status: ${{ needs.build.result }}
            <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Run details</a>
